//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    public int CategoryID { get; set; }
    public string CategoryName { get; set; }
    public string Description { get; set; }
    public string Picture { get; set; }
    public string Active { get; set; }

    public virtual Product Products { get; set; }
}

public partial class Customer
{
    public int CustomerId { get; set; }
    public string CustomerName { get; set; }
    public string CustomerPassword { get; set; }
    public string CustomerEmail { get; set; }

    public virtual Order Orders { get; set; }
}

public partial class Order
{
    public int OrderID { get; set; }
    public string OrderName { get; set; }
    public Nullable<int> OrderPrice { get; set; }
    public Nullable<int> OrderQuantity { get; set; }
    public string OrderColor { get; set; }
    public string OrderShipDate { get; set; }
    public string OrderBillDate { get; set; }

    public virtual Product Product { get; set; }
    public virtual Customer Customer { get; set; }
}

public partial class Product
{
    public int ProductID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Picture { get; set; }
    public int CategoryID { get; set; }
    public int SupplierID { get; set; }
    public Nullable<int> Size { get; set; }
    public Nullable<int> UnitPrice { get; set; }

    public virtual Order Orders { get; set; }
    public virtual Category Category { get; set; }
}
